ingress:
  enabled: true
  ingressClassName: traefik
  host: longhorn.beaners.club
  tls: true
  tlsSecret: longhorn-tls
  path: /
  pathType: ImplementationSpecific
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
